//#define DEF_TOTALCHARACTERS		80	//100 <- original

#define DEF_TOTALCHARACTERS		120  // for CLEROTH - NEW MONSTERS
#define DEF_TOTALACTION			102

#define DEF_OBJECTSTOP			94
#define DEF_OBJECTMOVE			54
#define DEF_OBJECTRUN			63
#define DEF_OBJECTATTACK		22
#define DEF_OBJECTMAGIC			41
#define DEF_OBJECTGETITEM		88
#define DEF_OBJECTDAMAGE		23
#define DEF_OBJECTDAMAGEMOVE	14
#define DEF_OBJECTATTACKMOVE	32
#define DEF_OBJECTDYING			45			   
#define DEF_OBJECTNULLACTION	100
#define DEF_OBJECTDEAD			101


#define DEF_OBJECTMOVE_CONFIRM				1001
#define DEF_OBJECTMOVE_REJECT				1010
#define DEF_OBJECTMOTION_CONFIRM			1020
#define DEF_OBJECTMOTION_ATTACK_CONFIRM		1030
#define DEF_OBJECTMOTION_REJECT				1040


